spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
#if there is a username and password
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword

#spring doesnt do auto indexing by itself
spring.data.mongodb.auto-index-creation=true