spring.data.mongodb.uri=mongodb+srv://jaygole2004_db_user:6C3DMJfZdQD24rXc@cluster0.3h60hjp.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journaldb
#if there is a username and password
#spring.data.mongodb.username=myjournaluser
#spring.data.mongodb.password=mypassword

#spring doesnt do auto indexing by itself
spring.data.mongodb.auto-index-creation=true